# 1．Pythonの基本 ｜Pythonプログラミングを使った統計分析の基礎

### [Logics of Blue](https://logics-of-blue.com/) 馬場真哉：2019年3月1日

## 目的
- Jupyter Notebookの基本的な使い方を学ぶ
    - インストール
    - 立ち上げ
    - 新規ファイル追加
    - Mark Downの使い方
- Pythonの基本文法を学ぶ
    - 四則演算
    - 比較演算
    - 変数と関数
    - クラスとインスタンス
    - 分析用ライブラリ（numpy・pandas・scipy）
    - 基本的な構文（if構文・forループ）
 
## 目次
1. [ソフトウェアのインストール](#1.-ソフトウェアのインストール)
2. [Jupyter Notebookの基本的な使い方](#2.-Jupyter-Notebookの基本的な使い方)
3. [四則演算](#3．四則演算)
4. [比較演算](#4．比較演算)
5. [変数の利用](#5．変数の利用)
6. [関数の利用](#6．関数の利用)
7. [クラスとインスタンス](#7．クラスとインスタンス)
8. [pandasとDataFrameの初歩](#8．pandasとDataFrameの初歩)
9. [numpyとpandas](#9．numpyとpandas)
10. [DataFrameにおけるデータの抽出](#10．DataFrameにおけるデータの抽出)
11. [scipyによる統計処理](#11．scipyによる統計処理)
12. [if分岐](#12．if分岐)
13. [forループ](#13．forループ)

***
## 1. ソフトウェアのインストール
<p>
    今回の研修ではすべて準備が終わっています。<br>
    個人のPCなどで、新たに分析環境を構築する際の参考にお使いください。
</p>

### Anacondaのインストール
<p>
    Anacondaは「分析用のツールが一式入ったPythonの配布形態の1つ」です。Anacondaを1つインストールするだけで、Python・Jupyter Notebook・各種分析ライブラリが一式インストールされます。<br>
    今回のセミナーではWindows10の使用を前提としています。
</p>

<p>
    Anacondaは下記Webページからダウンロードできます。
</p>

[Download Anaconda Distribution](https://www.anaconda.com/download/)


<p>
    Pythonには2系と3系がありますが、基本的には3系を使います。<br>
    『Python 3.6 version』を選択してダウンロードします。<br>
</p>


***
## 2. Jupyter Notebookの基本的な使い方
<p>
    Jupyter Notebookは、Pythonのコードを書いて、結果をすぐに表示させることのできる、便利なソフトウェアです。<br>
    Jupyter Notebookの立ち上げやコードの実行方法、実行結果の保存方法などを説明します。
</p>

### 手順1．Jupyter Notebookの起動
<p>
    Windows10ならCortanaの検索ボックスに「Jupyter Notebook」と打ち込んでEnterキーを押下すると立ち上がります。<br>
    スタートメニューにピン止めしておくと便利です。
</p>

<p>
    Jupyter Notebookが起動すると、ブラウザが立ち上がります。Webアプリを使うような感覚で、実装をすることが可能です。<br>
    Jupyter Notebook起動と同時、コマンドプロンプトが立ち上がります。
</p>

### 手順2．新しいファイルを作る
<p>
    起動画面では『C:\Users\ユーザー名』のフォルダ内のファイル一覧が表示されているはずです。<br>
    このセミナーでは『Python_Stat_Seminar』というフォルダが用意されているはずなので、それを使用します。フォルダをクリックすると、移動できます。<br>
    メニューの『New▼』→『Python3』を選択すると、プログラムを書く画面が出てきます。<br>
    『In[ ]』と左端に書かれている場所にコードを書いていくことになります。この部分を『セル』と呼ぶことにします。
</p>


### 手順3．計算の実行方法
<p>
    「1＋1」の計算結果を得るためには、セルに`1 + 1`と入力してから『Shift ＋ Enter』を押下します。<br>
    『Shift ＋ Enter』を押下すると、コードが実行されてから、一つ下のセルにフォーカスが移動します。<br>
    移動させたくない場合は『Ctrl ＋ Enter』を押下します。
</p>


### 手順4．コメントの書き方
<p>
    行の先頭にシャープ『'#'』記号を入れることで、その行全体がコメント扱いになります。<br>
    コメント行のコードは実行されません。コードの説明を書くのに使います。
</p>

### 手順5．Markdownの書き方
<p>
    単なるコメントだけではなく、見出しや箇条書き等を挿入することができます。<br>
    この時の記法をMarkdownと呼びます。
</p>

<p>
    セルを選択中に、上部メニューから『Code▼』を押下して『Markdown』に変更することで、選択セルがMarkdown形式の記法を受けつけるようになります。<br>
    この説明文などもMarkdown形式で書かれています。
</p>

<p>
    Markdown記法は、このセミナーで紹介するには豊富過ぎる機能を有しています。<br>
    『jupyternotebook Markdown』等で検索すると様々な情報が出てくるでしょう。<br>
    セルをダブルクリックすると、どのような記法で書かれてあるか確認することができます。編集も可能です。<br>
    『Shift ＋ Enter』を押下すると、表題や箇条書きがきれいに表示されるようになります。
</p>

### 手順6．分析レポートの保存
<p>
    編集中のファイルを保存する場合は、『Ctrl ＋ S』を押下します。上書き保存のショートカットキーです。<br>
    ファイル名は、画面上部で指定できます。デフォルトでは『Untitled』という名称となっています。
    
</p>

<p>
    分析結果やMarkdownにより記載された内容は、HTMLなどの形式で配布することができます。<br>
    メニューから『File』→『Download as』→『HTML(.html)』を選択します。
</p>


### 手順7．Jupyter Notebookの終了
<p>
    Jupyter Notebook起動と同時に立ち上がったコマンドプロンプトにおいて「Ctrl + C」を押下すると、Jupyter Notebookが終了されます。
</p>


### その他
<p>
    ショートカットキーは『Esc + H』を押下することで確認できます。<br>
    よく使うショートカットキーを載せます。
</p>

- セルをマークダウン形式にする『Esc + M』
- セルの
    - コピー　『Esc + C』
    - ペースト『Esc + V』
    - 切り取り『Esc + X』
    - 挿入　　
        - 上側『Esc + A』
        - 下側『Esc + B』
- カーネルの再起動『Esc + 0 + 0』(0を連打)<br>
　→変数等をすべて開放することができます。<br>
 　 見た目は変わりませんが。Jupyter Notebookを再立ち上げしたのと同じ状況となります。

<p>
    ここまででJupyter Notebookの基本的な使い方の説明は終わりです。<br>
    質問を受け付けます
</p>

***
## 3．四則演算

<p>
    基本的な四則演算の方法を学びます。<br>
    1つのセルに1つ計算結果が出力されるように記述するときれいです。
</p>

In [1]:
# 足し算
1 + 1

2

In [2]:
# 引き算
5 - 1

4

In [3]:
# 掛け算
3 * 6

18

In [4]:
# 割り算
8 / 2

4.0

***
## 4．比較演算

<p>
    大小比較などを行います。<br>
    結果はTrueまたはFalseという真偽型で得られます。
</p>

In [5]:
# 1は0.99よりも大きいか？
1 > 0.99

True

In [6]:
# 1は0.99よりも小さいか？
1 < 0.99

False

In [7]:
# 2は2.5以上か？
2 >= 2.5

False

In [8]:
# 2は2以上か？
2 >= 2

True

In [9]:
# 2は2より大きいか？
2 > 2

False

In [10]:
# 3は2と等しいか？
3 == 2

False

In [11]:
# 3は2と異なるか？
3 != 2

True

***
## 5．変数の利用

<p>
    変数を使うことで、一時的に値を保存することができます。<br>
    計算結果や、データの読み込みの際等、頻繁に使います。
</p>

In [12]:
# xに3を代入
x = 3

In [13]:
# 中身の表示
x

3

In [14]:
# 変数の足し算
x + 2

5

In [15]:
# 変数の演算
x > 2

True

数値だけでなく、文字列も格納できます。<br>
文字列はダブルクォーテーションやシングルクォーテーションで囲みます。

In [16]:
mozi = "AA"

mozi

'AA'

In [17]:
mozi_2 = 'ABC'

mozi_2

'ABC'

***
## 6．関数の利用

<p>
    計算ロジックを保存したものを関数と呼びます。<br>
    統計分析用の様々な関数が用意されているので、今後しばしば活用します。
</p>

<p>
    ここでは、関数を作成する例を紹介していますが、関数の作成は今回のセミナーでは今後行いません。<br>
    ライブラリが提供してくれた関数の使い方の理解を深める目的で紹介します。
</p>

In [18]:
# dataに1を足す関数を自作する
def plus_one(data):
    return(data + 1)

In [19]:
# 関数の実行
plus_one(4)

5

In [20]:
# すでに用意されているsum関数（合計値を計算する関数）を利用する
sum([1,2,3])

6

### 分析イメージ(このコードは動きません)

##### データを読み込んで変数に格納
data = データ読み込み関数(ファイル名)

##### 分析用の関数を実行
分析関数(data)


***
## 7．クラスとインスタンス

<p>
    厳密な定義ではありませんが、「データの構造と計算ロジック」を共に指定したものをクラスと呼びます。<br>
    実際にデータを中に格納したものをインスタンスと呼びます。
</p>

<p>
    『__init__』という特殊な関数を定義することで、クラスの初期化をします。これをコンストラクタと呼びます。<br>
    クラスにデータを格納するために、コンストラクタが使われるとイメージすると良いでしょう。
</p>

<p>
    クラスを自分で定義することは、このセミナーの中では今後は行いません。<br>
    統計分析用の様々なクラスが用意されているので、それを使いまわします。
</p>

In [21]:
# クラスを自分で作ってみる
class Sample_Class:
    def __init__(self, data1, data2):
        self.data1 = data1
        self.data2 = data2
        
    def method2(self):
        return(self.data1 + self.data2)

In [22]:
# クラスにデータを格納して、インスタンスを生成する
sample_instance = Sample_Class(data1 = 2, data2 = 3)

In [23]:
# インスタンスの中に格納されているデータを取り出す
sample_instance.data1

2

In [24]:
# インスタンスの中に格納されているデータを取り出す
sample_instance.data2

3

In [25]:
# クラスが用意した関数を実行する
sample_instance.method2()

5

### 分析イメージ(このコードは動きません)

##### データを読み込んで変数に格納→データ格納用のクラスに、データを格納してインスタンスを生成する
data = データ読み込み関数(ファイル名)

##### 分析用の関数を実行
分析関数(data)　または<br>
data.クラスが用意した分析関数()


***
## 8．pandasとDataFrameの初歩
<p>
    pandasのDataFrameを使ってデータを読み込んで、簡単な分析を行います。
</p>

<p>
    pandasは様々な機能がつまったライブラリと呼ばれるものです。<br>
    ライブラリを読み込むことで、pandasが用意した様々なクラスや関数を流用することができます。<br>
    こういった便利なライブラリがたくさんあるので、Pythonはデータ分析に適した言語だと言われています。
</p>

In [26]:
# pandasをimportします。これでpandasの用意したクラスや関数を使うことができます。
# 『as pd』と指定することで、pdという略称を使ってpandasの機能を参照できるようになります。
import pandas as pd

In [27]:
# データを読み込んで、変数に格納します。
sales_data = pd.read_csv("sample_data.csv")

# 格納されたデータを表示する
sales_data

sales
0      1
1      2
2      3
3      4
4      5

In [28]:
# ちなみに、sales_dataという変数は、DataFrameクラスのインスタンスとなっています。
# DataFrameクラスという便利なクラスをpandasが提供してくれている。
# それのインスタンスを生成してデータを保存しています。
type(sales_data)

pandas.core.frame.DataFrame

In [29]:
# dataの集計処理を行います。DataFrameクラスがもつdescribe()関数を使います。
# 売り上げデータの、サンプルサイズ・平均・標準偏差（不偏分散の平方根）・
# 最小・第1四分位点・中央値・第3四分位点・最大値が一気に計算されます。
sales_data.describe()

sales
count  5.000000
mean   3.000000
std    1.581139
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    5.000000

<p>
    Pythonあるいはライブラリが用意してくれた便利なクラス・関数を使うことで、<br>
    ほとんどコードを書くことなく、数行で簡単な集計処理が終わってしまいます。
</p>


<p>
    Pythonによるデータ分析のイメージはつかめましたか？<br>
    ここまでで、一度質問を受け付けます。
</p>

***
## 9．numpyとpandas
<p>
    先ほどはデータをファイルから読み込みましたが、今度は自分でデータを作ってみましょう。<br>
    numpyというライブラリのndarrayというクラスを使うことで、様々なデータを簡単に作成することができます。<br>
    ndarrayをpandasのDataFrameにまとめることもできます。
</p>

In [30]:
# 数値計算に使うライブラリ
import numpy as np
import pandas as pd

In [31]:
# 複数の数値をまとめたndarray
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [32]:
# サンプルサイズ
len(data)

5

In [33]:
# 1~9までの等差数列の作成
# ここでは紹介しませんが、データを生成する様々な関数がnumpyには用意されています。
np.arange(start = 1, stop = 10, step = 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# numpyのndarrayをDataFrameにまとめます
data_1 = np.array([1, 2, 3, 4, 5])
index_1 = np.array(["A", "A", "B", "B", "C"])

# DataFrameの作成
df = pd.DataFrame({
    "column1":data_1,
    "column2":index_1
})

# 結果の表示
df

column1 column2
0        1       A
1        2       A
2        3       B
3        4       B
4        5       C

***
## 10．DataFrameにおけるデータの抽出
<p>
    データの抽出は、分析をする際の重要な作業ですが、やや手間がかかります。<br>
    整然データならば、データの抽出をする手間が省けることがあります。<br>
    ここでは、ごく初歩的なDataFrameにおけるデータの抽出処理を学びます。
</p>

In [35]:
# DataFrameの1列だけを取り出すと、arrayのように使えます
# これをSeries型のデータと呼びます。
df.column1

0    1
1    2
2    3
3    4
4    5
Name: column1, dtype: int32

In [36]:
# 先頭行を抽出
df.head(n = 3)

column1 column2
0        1       A
1        2       A
2        3       B

In [37]:
# column2がAのデータのみを抽出
df.query('column2 == "A"')

column1 column2
0        1       A
1        2       A

In [38]:
# column2がAまたはCのデータのみを抽出
df.query('column2 == "A" | column2 == "C"')

column1 column2
0        1       A
1        2       A
4        5       C

In [39]:
# column1が2かつ、column2がAのデータのみを抽出
df.query('column1 == 2 & column2 == "A"')

column1 column2
1        2       A

***
## 11．scipyによる統計処理
<p>
   scipyは様々なデータ分析用の関数を提供してくれるライブラリです。<br>
    詳しくは実際に分析を行う際に説明しますが、分析用関数の例をいくつか紹介します。
</p>

In [40]:
# ライブラリの読み込み
import scipy as sp
from scipy import stats

In [41]:
# データの用意
sample_data = np.array([1,2,3,4,5])
sample_data

array([1, 2, 3, 4, 5])

In [42]:
# 不偏分散の計算
sp.var(sample_data, ddof = 1)

2.5

In [43]:
# 標準偏差の計算
sp.std(sample_data, ddof = 1)

1.5811388300841898

In [44]:
# 標準誤差の計算１

# 不偏分散
var = sp.var(sample_data, ddof = 1)

# サンプルサイズ
N = len(sample_data)

# 標準誤差
standard_error = sp.sqrt(var / N)
standard_error

0.7071067811865476

In [45]:
# 標準誤差の計算２
# scipyの中のさらにstatsという機能群（モジュール）を使います。
stats.sem(sample_data)

0.7071067811865476

***
## 12．if分岐

<p>
    条件に応じて結果を変える場合には、if構文を使います。<br>
    皆さんに実装してもらうことはありませんが、シミュレーションをする際に活用します。
</p>

In [46]:
data = 1

if(data < 2):
    print("2より小さいデータです")
else:
    print("2以上のデータです")

2より小さいデータです


In [47]:
data = 3

if(data < 2):
    print("2より小さいデータです")
else:
    print("2以上のデータです")

2以上のデータです


***
## 13．forループ

<p>
    似たような処理を連続で繰り返すときにはforループという構文を使います。<br>
    皆さんに実装してもらうことはありませんが、シミュレーションをする際に活用します。
</p>

In [48]:
# iを0,1,2と「0始まりで3つの幅」で変化させて、iを出力
for i in range(0, 3):
    print(i)

0
1
2


In [49]:
# iを3,6,9と「3始まりで10まで、3つずつ増やす」で変化させて、iを出力
for i in range(3, 10, 3):
    print(i)

3
6
9


In [50]:
# Aという文字列を5回出力
for i in range(0,5):
    print("A")

A
A
A
A
A


In [51]:
# 以下の結果と同じ
print("A")
print("A")
print("A")
print("A")
print("A")

A
A
A
A
A


<p>
    Pythonによるプログラミングのイメージはつかめましたか？<br>
    ここまでで、一度質問を受け付けます。
</p>